api/urls.py
from django.urls import path

from api import views

app_name = "api"


urlpatterns = [
    path('ws/categories/', views.WSCategory.as_view(), name="ws_categories"),
    ###### CLIENT'S URLS #####
    path('ws/categories/client/', views.WSClient.as_view(), name="ws_client"),
    path('v2/client/create/category/', views.CreateCategoryClient.as_view(), name="api_create_category"),
    ##### APIS URLS #####
    path('v2/list/categories/', views.CategoryListAPIView.as_view(), name="api_list_category"),
    path('v2/create/category/', views.CreateCategoryAPIView.as_view(), name="api_create_category"),
]

fplaest/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("home.urls")),
    path('core/', include("core.urls")),
    path('api/', include("api.urls")),
]

home/urls.py
from django.urls import path

from home import views


app_name = "home"

urlpatterns = [
    path('', views.Index.as_view(), name="index"),
    path('about/', views.About.as_view(), name="about"),
    path('contact/', views.Contact.as_view(), name="contact"),
    path('logout/', views.Logout.as_view(), name="logout"),

    ## USERS URL
    path('signup/', views.SignUp.as_view(), name="signup"),
    path('detail/profile/<int:pk>/', views.DetailProfile.as_view(), name="detail_profile"),
    path('update/profile/<int:pk>/', views.UpdateProfile.as_view(), name="update_profile"),
]

home/models.py
from django.db import models
from django.contrib.auth.models import User
from django.dispatch import receiver
from django.db.models.signals import post_save

# Create your models here.

class UserPrueba(models.Model):
    first_name = models.CharField(max_length=16, default="Gost User", blank=True, null=True)
    last_name = models.CharField(max_length=16, default="Phantom User")
    age = models.IntegerField(default=1)
    weight = models.FloatField(default=1.5)
    status = models.BooleanField(default=True)
    timestamp = models.DateField(auto_now_add=True)

    def __str__(self):
        return self.first_name


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=32, default="Generic User", blank=True, null=True)
    age = models.IntegerField(default=0, blank=True, null=True)
    email = models.EmailField(default="user@email.com", blank=True, null=True)
    avatar = models.ImageField(upload_to="users/profiles", default="avatar.png", blank=True, null=True)
    bio = models.CharField(max_length=256, default="I Love this APP", blank=True, null=True)
    status = models.BooleanField(default=True)
    
    def __str__(self):
        return self.user.username


@receiver(post_save, sender=User)
def update_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)
    instance.profile.save()

home/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from .models import Profile

class LoginForm(forms.Form):
    username = forms.CharField(widget=forms.TextInput(attrs={"type":"text", "class":"form-control","placeholder":"Escribe tu username"}))
    password = forms.CharField(widget=forms.PasswordInput(attrs={"type":"password", "class":"form-control","placeholer":"Escribe tu Password"}))


class UserForm(UserCreationForm):
    username = forms.CharField(max_length=32, widget=forms.TextInput(attrs={"type":"text", "class":"form-control", "placeholder":"Escribe tu Username"}))
    password1 = forms.CharField(max_length=32, widget=forms.PasswordInput(attrs={"type":"password", "class":"form-control", "placeholder":"Escribe tu Password"}))
    password2 = forms.CharField(max_length=32, widget=forms.PasswordInput(attrs={"type":"password", "class":"form-control", "placeholder":"Confirma tu Password"}))
    first_name = forms.CharField(max_length=32, widget=forms.TextInput(attrs={"type":"text", "class":"form-control", "placeholder":"Escribe tu First Name"}))
    last_name = forms.CharField(max_length=32, widget=forms.TextInput(attrs={"type":"text", "class":"form-control", "placeholder":"Escribe tu Last Name"}))
    email = forms.CharField(max_length=32, widget=forms.TextInput(attrs={"type":"text", "class":"form-control", "placeholder":"Escribe tu Email"}))
    
    class Meta:
        model = User
        fields = [
            "username",
            "password1",
            "password2",
            "first_name",
            "last_name",
            "email"
        ]

        # widgets = {
        #     "username": forms.TextInput(attrs={"type":"text", "class":"form-control", "placeholder":"Escribe tu Username"}),
        #     "password": forms.PasswordInput(attrs={"type":"password", "class":"form-control", "placeholder":"Escribe tu Password"}),
        #     "email": forms.TextInput(attrs={"type":"text", "class":"form-control", "placeholder":"Escribe tu Email"}),
        # }



class UpdateProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = "__all__"

home/views.py
from django.shortcuts import render, redirect
from django.urls import reverse_lazy, reverse

from django.views import generic
from django.contrib.auth.models import User
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth import logout, login, authenticate

from .forms import LoginForm, UserForm, UpdateProfileForm
from .models import Profile

# Create your views here.

# class Index(generic.View):
#     template_name = "home/index.html"
#     context = {}

#     def get(self, request):
#         return render(request, self.template_name, self.context)



class About(generic.View):
    template_name = "home/about.html"
    context = {}

    def get(self, request, *args, **kwargs):
        return render(request, self.template_name, self.context)


class Contact(generic.View):
    template_name = "home/contact.html"
    context = {}

    def get(self, request, *args, **kwargs):
        return render(request, self.template_name, self.context)



class Index(generic.View):
    template_name = "home/index.html"
    context ={}
    form = LoginForm()

    def get(self, request):
        self.context = {
            "form": self.form
        }
        return render(request, self.template_name, self.context)
    
    def post(self, request):
        username = request.POST["username"]
        password = request.POST["password"]
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect('/')
        else:
            return redirect('/')    
        


class Logout(generic.View):
    def get(self, request):
        logout(request)
        return redirect('/')


#### USER SIGNUP AND PROFILE ####
class SignUp(generic.CreateView):
    template_name = "home/signup.html"
    form_class = UserForm
    success_url = reverse_lazy("home:index")

    def form_valid(self, form):
        form.save()
        username = form.cleaned_data.get("username")
        password1 = form.cleaned_data.get("password1")
        user = authenticate(self.request, username=username, password=password1)
        if user is not None:
            login(self.request, user)
        id = form.cleaned_data.get("id")
        print(id)
        return redirect("home:index")




class DetailProfile(generic.View):
    template_name = "home/detail_profile.html"
    context = {}

    def get(self, request, pk):
        self.context = {
            "profile": Profile.objects.get(id=pk)
        }
        return render(request, self.template_name, self.context)



class UpdateProfile(generic.UpdateView):
    template_name = "home/update_profile.html"
    model = Profile
    form_class = UpdateProfileForm
    success_url = reverse_lazy("home:detail_profile")

    def get_success_url(self):
        pk = self.kwargs["pk"]
        return reverse("home:detail_profile", kwargs={"pk":pk})

templates/home/about.html
{% extends "base/base.html" %}

{% block title %}About View{% endblock title %}

{% block content %}
  <h1>Hola Soy el About con Extends</h1>
{% endblock content %}

templates/home/contact.html
{% extends "base/base.html" %}

{% block title %}
  Contact View 
{% endblock title %}

{% block content %}
  <h1>Soy el contact con herencia</h1>
{% endblock content %}

templates/home/detail_profile.html
{% extends "base/base.html" %}

{% block title %}
  PROFILE VIEW
{% endblock title %}

{% block content %}
    <div class="card border-primary mb-3" style="max-width: 20rem;">
      <div class="card-header">{{ profile }}</div>
      <div class="card-body">
        <h4 class="card-title">{{ profile.user.first_name }}</h4>
        <p class="card-text">{{ profile.bio }}.</p>
     </div>
    </div>
    <a href="{% url 'home:update_profile' profile.id %}" class="btn btn-outline-warning">Update Profile</a>
{% endblock content %}

templates/home/index.html
{% extends 'base/base.html' %}

{% block title %}Index View{% endblock title %}

{% block content %}
    {% if request.user.is_authenticated %}
        <h1>Bienvenido {{ user }}!</h1>
        <a href="{% url 'home:logout' %}" class="btn btn-link">LogOut</a>
        <table class="table">
            <thead>
                <th>Item 1</th>
                <th>Item 2</th>
                <th>Item 3</th>
            </thead>
            <tbody>
                <tr>
                    <td>Uno</td>
                    <td>Dos</td>
                    <td>Tres</td>
                </tr>
                <tr>
                    <td>Cuatro</td>
                    <td>Cinco</td>
                    <td>Seis</td>
                </tr>
                <tr>
                    <td>Siete</td>
                    <td>Ocho</td>
                    <td>Nueve</td>
                </tr>
            </tbody>
        </table>
    {% else %}
    <br>
        <form action="" method="post">
            {% csrf_token %}
                {{ form }}
                <br><hr>
                <button type="submit" class="btn btn-outline-success form-control">LogIn</button>                
        </form>
        <p>
            Si no tienes una cuenta Registrate:
            <a href="{% url 'home:signup' %}" class="btn btn-link">SignUp</a>
        </p>
        
    {% endif %}
{% endblock content %}

templates/home/signup.html
{% extends "base/base.html" %}

{% block title %}
  SIGNUP VIEW
{% endblock title %}

{% block content %}
  <form action="" method="post" class="form">
    {% csrf_token %}
        {{ form }}
        <button type="submit" class="btn btn-outline-success">New User SignUp</button>
        <a href="{% url 'home:index' %}" class="btn btn-outline-warning">Cancel</a>
  </form>
{% endblock content %}

templates/home/update_profile.html
{% extends "base/base.html" %}

{% block title %}
  PROFILE UPDATE VIEW VIEW
{% endblock title %}

{% block content %}
  <form action="" method="post" class="form">
    {% csrf_token %}
        {{ form }}
        <button type="submit" class="btn btn-outline-success">Update Profile</button>
        <a href="{{ request.META.HTTP_REFERER }}" class="btn btn-outline-warning">Cancel</a>
  </form>
{% endblock content %}